In [1]:
import json

with open(r'hackdavis2024-default-rtdb-export.json', 'r') as f:
    d = json.load(f)
d

{'04:51:52': {'epochTime': 1714279912, 'off': 407, 'on': 887},
 '04:51:55': {'epochTime': 1714279915, 'off': 409, 'on': 884},
 '04:51:59': {'epochTime': 1714279919, 'off': 142, 'on': 868},
 '04:52:01': {'epochTime': 1714279921, 'off': 217, 'on': 817},
 '04:52:03': {'epochTime': 1714279923, 'off': 356, 'on': 821},
 '04:52:05': {'epochTime': 1714279925, 'off': 315, 'on': 808},
 '04:52:07': {'epochTime': 1714279927, 'off': 153, 'on': 851},
 '04:52:10': {'epochTime': 1714279930, 'off': 142, 'on': 806},
 '04:52:12': {'epochTime': 1714279932, 'off': 142, 'on': 830},
 '04:52:14': {'epochTime': 1714279934, 'off': 142, 'on': 807},
 '04:52:16': {'epochTime': 1714279936, 'off': 307, 'on': 778},
 '04:52:18': {'epochTime': 1714279938, 'off': 142, 'on': 799},
 '04:52:21': {'epochTime': 1714279941, 'off': 142, 'on': 804},
 '04:52:24': {'epochTime': 1714279944, 'off': 216, 'on': 795},
 '04:52:27': {'epochTime': 1714279947, 'off': 340, 'on': 856},
 '04:52:29': {'epochTime': 1714279949, 'off': 142, 'on': 839},
 '04:52:45': {'epochTime': 1714279965, 'off': 142, 'on': 804},
 '04:52:48': {'epochTime': 1714279968, 'off': 272, 'on': 844},
 '04:52:51': {'epochTime': 1714279971, 'off': 142, 'on': 793},
 '04:52:53': {'epochTime': 1714279973, 'off': 233, 'on': 838},
 '04:52:55': {'epochTime': 1714279975, 'off': 355, 'on': 844},
 '04:52:57': {'epochTime': 1714279977, 'off': 274, 'on': 806},
 '04:52:59': {'epochTime': 1714279979, 'off': 238, 'on': 801},
 '04:54:59': {'epochTime': 1714280099, 'off': 142, 'on': 701},
 '04:55:02': {'epochTime': 1714280102, 'off': 142, 'on': 711},
 '04:55:04': {'epochTime': 1714280104, 'off': 341, 'on': 791},
 '04:55:08': {'epochTime': 1714280108, 'off': 181, 'on': 749},
 '04:55:10': {'epochTime': 1714280110, 'off': 180, 'on': 740},
 '04:55:13': {'epochTime': 1714280113, 'off': 241, 'on': 798},
 '04:55:15': {'epochTime': 1714280115, 'off': 280, 'on': 740},
 '04:55:18': {'epochTime': 1714280118, 'off': 142, 'on': 715},
 '04:55:20': {'epochTime': 1714280120, 'off': 277, 'on': 711},
 '04:55:23': {'epochTime': 1714280123, 'off': 142, 'on': 789},
 '04:55:26': {'epochTime': 1714280126, 'off': 142, 'on': 740},
 '04:55:31': {'epochTime': 1714280131, 'off': 164, 'on': 714},
 '04:55:36': {'epochTime': 1714280136, 'off': 142, 'on': 691},
 '04:55:40': {'epochTime': 1714280140, 'off': 152, 'on': 765},
 '04:55:42': {'epochTime': 1714280142, 'off': 282, 'on': 738},
 '04:55:45': {'epochTime': 1714280145, 'off': 142, 'on': 778},
 '04:55:55': {'epochTime': 1714280155, 'off': 254, 'on': 699},
 '04:55:57': {'epochTime': 1714280157, 'off': 142, 'on': 723},
 '04:56:00': {'epochTime': 1714280160, 'off': 311, 'on': 721},
 '04:57:04': {'epochTime': 1714280224, 'off': 492, 'on': 876},
 '04:57:06': {'epochTime': 1714280226, 'off': 142, 'on': 825},
 '04:57:08': {'epochTime': 1714280228, 'off': 142, 'on': 838},
 '04:57:10': {'epochTime': 1714280230, 'off': 157, 'on': 848},
 '04:57:13': {'epochTime': 1714280233, 'off': 198, 'on': 804},
 '04:57:15': {'epochTime': 1714280235, 'off': 336, 'on': 855},
 '04:57:17': {'epochTime': 1714280237, 'off': 181, 'on': 827},
 '04:57:20': {'epochTime': 1714280240, 'off': 313, 'on': 816},
 '04:57:23': {'epochTime': 1714280243, 'off': 142, 'on': 804},
 '04:57:26': {'epochTime': 1714280246, 'off': 142, 'on': 802},
 '04:57:28': {'epochTime': 1714280248, 'off': 325, 'on': 804},
 '04:57:30': {'epochTime': 1714280250, 'off': 183, 'on': 787},
 '04:57:32': {'epochTime': 1714280252, 'off': 213, 'on': 821},
 '04:57:35': {'epochTime': 1714280255, 'off': 241, 'on': 793},
 '04:57:37': {'epochTime': 1714280257, 'off': 142, 'on': 840},
 '04:57:39': {'epochTime': 1714280259, 'off': 142, 'on': 800},
 '04:57:42': {'epochTime': 1714280262, 'off': 142, 'on': 842},
 '04:57:44': {'epochTime': 1714280264, 'off': 142, 'on': 845},
 '04:57:47': {'epochTime': 1714280267, 'off': 230, 'on': 804},
 '04:57:49': {'epochTime': 1714280269, 'off': 181, 'on': 817},
 '04:57:51': {'epochTime': 1714280271, 'off': 142, 'on': 802},
 '04:57:53': {'epochTime': 1714280273, 'off': 238, 'on': 813},
 '04:57:56': {'epochTime': 1714280276, 'off': 203, 'on': 830},
 '04:57:59': {'epochTime': 1714280279, 'off': 142, 'on': 780}}

In [3]:
hari = {key:value for key, value in d.items() if "4:52" in key}
aarav = {key:value for key, value in d.items() if "4:55" in key}
harsh = {key:value for key, value in d.items() if "4:57" in key}
print(len(hari), len(aarav), len(harsh))
hari

20 17 24

{'04:52:01': {'epochTime': 1714279921, 'off': 217, 'on': 817},
 '04:52:03': {'epochTime': 1714279923, 'off': 356, 'on': 821},
 '04:52:05': {'epochTime': 1714279925, 'off': 315, 'on': 808},
 '04:52:07': {'epochTime': 1714279927, 'off': 153, 'on': 851},
 '04:52:10': {'epochTime': 1714279930, 'off': 142, 'on': 806},
 '04:52:12': {'epochTime': 1714279932, 'off': 142, 'on': 830},
 '04:52:14': {'epochTime': 1714279934, 'off': 142, 'on': 807},
 '04:52:16': {'epochTime': 1714279936, 'off': 307, 'on': 778},
 '04:52:18': {'epochTime': 1714279938, 'off': 142, 'on': 799},
 '04:52:21': {'epochTime': 1714279941, 'off': 142, 'on': 804},
 '04:52:24': {'epochTime': 1714279944, 'off': 216, 'on': 795},
 '04:52:27': {'epochTime': 1714279947, 'off': 340, 'on': 856},
 '04:52:29': {'epochTime': 1714279949, 'off': 142, 'on': 839},
 '04:52:45': {'epochTime': 1714279965, 'off': 142, 'on': 804},
 '04:52:48': {'epochTime': 1714279968, 'off': 272, 'on': 844},
 '04:52:51': {'epochTime': 1714279971, 'off': 142, 'on': 793},
 '04:52:53': {'epochTime': 1714279973, 'off': 233, 'on': 838},
 '04:52:55': {'epochTime': 1714279975, 'off': 355, 'on': 844},
 '04:52:57': {'epochTime': 1714279977, 'off': 274, 'on': 806},
 '04:52:59': {'epochTime': 1714279979, 'off': 238, 'on': 801}}

In [4]:
import json
from datetime import datetime
import pandas as pd

# Sample data in JSON format (replace with your actual JSON data)
data = hari

# Convert data to DataFrame
rows = []
for time_str, values in data.items():
    row = {
        'timestamp': datetime.strptime(time_str, '%H:%M:%S'),
        'epochTime': values['epochTime'],
        'off': values['off'],
        'on': values['on'],
        'difference': values['on'] - values['off']
    }
    rows.append(row)

df = pd.DataFrame(rows)

# Set timestamp as index
df.set_index('timestamp', inplace=True)

# Group by minute and calculate averages
result = df.resample('T').agg({
    'on': 'mean',
    'difference': 'mean'
})

result

                         on  difference
timestamp
1900-01-01 04:52:00  817.05      596.45

In [5]:
import json
from datetime import datetime
import pandas as pd

# Sample data in JSON format (replace with your actual JSON data)
data = aarav

# Convert data to DataFrame
rows = []
for time_str, values in data.items():
    row = {
        'timestamp': datetime.strptime(time_str, '%H:%M:%S'),
        'epochTime': values['epochTime'],
        'off': values['off'],
        'on': values['on'],
        'difference': values['on'] - values['off']
    }
    rows.append(row)

df = pd.DataFrame(rows)

# Set timestamp as index
df.set_index('timestamp', inplace=True)

# Group by minute and calculate averages
result = df.resample('T').agg({
    'on': 'mean',
    'difference': 'mean'
})

result

                             on  difference
timestamp
1900-01-01 04:55:00  740.705882  543.882353

In [6]:
import json
from datetime import datetime
import pandas as pd

# Sample data in JSON format (replace with your actual JSON data)
data = harsh

# Convert data to DataFrame
rows = []
for time_str, values in data.items():
    row = {
        'timestamp': datetime.strptime(time_str, '%H:%M:%S'),
        'epochTime': values['epochTime'],
        'off': values['off'],
        'on': values['on'],
        'difference': values['on'] - values['off']
    }
    rows.append(row)

df = pd.DataFrame(rows)

# Set timestamp as index
df.set_index('timestamp', inplace=True)

# Group by minute and calculate averages
result = df.resample('T').agg({
    'on': 'mean',
    'difference': 'mean'
})

result

                             on  difference
timestamp
1900-01-01 04:57:00  819.708333  615.083333